#Import Files

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
import sys
sys.modules['sklearn.externals.joblib'] = joblib
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier

plt.show()

In [ ]:
df = pd.read_csv("/content/diabetic_disease.csv")

#Backward Elimination

In [ ]:
df.shape

(768, 9)

In [ ]:
X = df.iloc[:,0:8].values
Y = df.iloc[:,-1].values

In [ ]:
df.iloc[:,0:8]

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1.0     85.0           66.0           29.0    102.5  26.6   
1            1.0     89.0           66.0           23.0     94.0  28.1   
2            5.0    116.0           74.0           27.0    102.5  25.6   
3           10.0    115.0           70.0           27.0    102.5  35.3   
4            4.0    110.0           92.0           27.0    102.5  37.6   
..           ...      ...            ...            ...      ...   ...   
763          1.0    128.0           88.0           39.0    110.0  36.5   
764          5.0    123.0           72.0           32.0    169.5  36.3   
765          6.0    190.0           92.0           32.0    169.5  35.5   
766          9.0    170.0           74.0           31.0    169.5  44.0   
767          1.0    126.0           60.0           32.0    169.5  30.1   

     DiabetesPedigreeFunction  Age  
0                       0.351   31  
1                       0.167   21  
2                       0.201   30  
3                       0.134   29  
4                       0.191   30  
..                        ...  ...  
763                     1.057   37  
764                     0.258   52  
765                     0.278   66  
766                     0.403   43  
767                     0.349   47  

[768 rows x 8 columns]

In [ ]:
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state=0)

In [ ]:
backward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=4,forward = False, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   19.3s finished

[2023-04-12 07:54:40] Features: 7/4 -- score: 0.8957958751983078[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   17.2s finished

[2023-04-12 07:54:57] Features: 6/4 -- score: 0.8957958751983076[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   13.5s finished

[2023-04-12 07:55:10] Features: 5/4 -- score: 0.8909307244843998[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 

In [ ]:
backward_feature_selector.k_feature_idx_

(1, 4, 5, 7)

In [ ]:
backward_feature_selector.k_feature_names_

('1', '4', '5', '7')

In [ ]:
backward_feature_selector.k_score_

0.8957429931253305

In [ ]:
backward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=(1,8),forward = False, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   18.4s finished

[2023-04-12 07:57:25] Features: 7/1 -- score: 0.8974087784241143[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   16.9s finished

[2023-04-12 07:57:42] Features: 6/1 -- score: 0.8975145425700687[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   13.6s finished

[2023-04-12 07:57:56] Features: 5/1 -- score: 0.889344262295082[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 o

In [ ]:
backward_feature_selector.k_feature_names_

('0', '1', '2', '3', '4', '7')

In [ ]:
backward_feature_selector.k_score_


0.8975145425700687

In [ ]:
backward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=5,forward = False, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   18.1s finished

[2023-04-12 07:59:04] Features: 7/5 -- score: 0.895848757271285[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   15.8s finished

[2023-04-12 07:59:20] Features: 6/5 -- score: 0.8925436277102061[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   13.7s finished

[2023-04-12 07:59:34] Features: 5/5 -- score: 0.8909571655208884

In [ ]:
backward_feature_selector.k_feature_idx_

(1, 3, 4, 5, 7)

In [ ]:
backward_feature_selector.k_score_

0.8909571655208884

In [ ]:
backward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=6,forward = False, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   18.1s finished

[2023-04-12 08:00:33] Features: 7/6 -- score: 0.899074563722898[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   17.2s finished

[2023-04-12 08:00:50] Features: 6/6 -- score: 0.895848757271285

In [ ]:
backward_feature_selector.k_feature_idx_

(0, 1, 4, 5, 6, 7)

In [ ]:
backward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=7,forward = False, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   17.9s finished

[2023-04-12 08:01:25] Features: 7/7 -- score: 0.8991274457958752

In [ ]:
backward_feature_selector.k_feature_idx_

(0, 1, 3, 4, 5, 6, 7)

In [ ]:
backward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=3,forward = False, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   18.2s finished

[2023-04-12 08:03:24] Features: 7/3 -- score: 0.8924907456372289[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   16.1s finished

[2023-04-12 08:03:40] Features: 6/3 -- score: 0.8941565309360126[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   13.9s finished

[2023-04-12 08:03:54] Features: 5/3 -- score: 0.889344262295082[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 o

In [ ]:
backward_feature_selector.k_feature_idx_

(0, 4, 7)

#Forward_Selection

In [ ]:
forward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=5,forward = True, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   18.0s finished

[2023-04-12 08:05:57] Features: 1/5 -- score: 0.8143574828133264[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   16.0s finished

[2023-04-12 08:06:13] Features: 2/5 -- score: 0.874457958751983[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   13.4s finished

[2023-04-12 08:06:26] Features: 3/5 -- score: 0.8893442622950818[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 o

In [ ]:
forward_feature_selector.k_feature_idx_

(0, 1, 3, 4, 7)

In [ ]:
forward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=6,forward = True, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   17.1s finished

[2023-04-12 08:07:19] Features: 1/6 -- score: 0.8110787942887361[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.9s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   15.0s finished

[2023-04-12 08:07:34] Features: 2/6 -- score: 0.8680063458487572[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   13.2s finished

[2023-04-12 08:07:47] Features: 3/6 -- score: 0.887704918032787[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 o

In [ ]:
forward_feature_selector.k_feature_idx_

(1, 2, 4, 5, 6, 7)

In [ ]:
forward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=7,forward = True, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   17.0s finished

[2023-04-12 08:08:53] Features: 1/7 -- score: 0.8159703860391326[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   15.6s finished

[2023-04-12 08:09:09] Features: 2/7 -- score: 0.8696721311475409[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.7s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   12.8s finished

[2023-04-12 08:09:22] Features: 3/7 -- score: 0.8925965097831835[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 

In [ ]:
forward_feature_selector.k_feature_idx_

(0, 1, 2, 3, 4, 5, 7)

In [ ]:
forward_feature_selector.k_score_

0.8941829719725012

In [ ]:
forward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=3,forward = True, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   19.1s finished

[2023-04-12 08:34:52] Features: 1/3 -- score: 0.8159968270756213[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.5s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   16.8s finished

[2023-04-12 08:35:09] Features: 2/3 -- score: 0.8712585933368588[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.6s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   14.2s finished

[2023-04-12 08:35:23] Features: 3/3 -- score: 0.8893178212585934

In [ ]:
forward_feature_selector.k_feature_idx_

(1, 4, 7)

In [ ]:
forward_feature_selector.k_score_

0.8893178212585934

In [ ]:
forward_feature_selector = SFS(RandomForestClassifier(n_jobs=-1),k_features=2,forward = True, floating=False, verbose=2, scoring="accuracy", cv=10).fit(X_train,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   18.3s finished

[2023-04-12 08:36:10] Features: 1/2 -- score: 0.8192755156002116[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   17.2s finished

[2023-04-12 08:36:27] Features: 2/2 -- score: 0.8680063458487572

In [ ]:
forward_feature_selector.k_feature_idx_

(4, 7)

#Exhaustive feature Selection

In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
efs = ExhaustiveFeatureSelector(RandomForestClassifier(n_jobs=-1),min_features=1,max_features = 8,scoring="accuracy", cv=10).fit(X_train,y_train)

Features: 255/255

In [ ]:
efs.best_feature_names_

('0', '4', '5', '7')

In [ ]:
efs.best_score_

0.899074563722898

In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
efs = ExhaustiveFeatureSelector(RandomForestClassifier(n_jobs=-1),min_features=1,max_features = 7,scoring="accuracy", cv=10).fit(X_train,y_train)

Features: 254/254

In [ ]:
efs.best_feature_names_

('1', '4', '5', '7')

In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
efs = ExhaustiveFeatureSelector(RandomForestClassifier(n_jobs=-1),min_features=1,max_features = 6,scoring="accuracy", cv=10).fit(X_train,y_train)

Features: 246/246

In [ ]:
efs.best_feature_names_

('1', '3', '4', '5', '7')

In [ ]:
efs.best_score_

0.895848757271285

In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
efs = ExhaustiveFeatureSelector(RandomForestClassifier(n_jobs=-1),min_features=1,max_features = 5,scoring="accuracy", cv=10).fit(X_train,y_train)

Features: 218/218

In [ ]:
efs.best_feature_names_

('0', '1', '4', '5', '7')

In [ ]:
efs.best_score_

0.8974616604970913

In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
efs = ExhaustiveFeatureSelector(RandomForestClassifier(n_jobs=-1),min_features=1,max_features = 4,scoring="accuracy", cv=10).fit(X_train,y_train)

Features: 162/162

In [ ]:
efs.best_score_

0.8908778424114224

In [ ]:
efs.best_feature_names_

('1', '4', '5', '7')

#Recursive feature elimination

In [ ]:
from sklearn.feature_selection import RFE


In [ ]:
rfe = RFE(estimator=RandomForestClassifier(n_jobs=-1),n_features_to_select=4)
rfe.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1), n_features_to_select=4)

In [ ]:
rfe.ranking_

array([3, 1, 5, 1, 1, 2, 4, 1])

In [ ]:
rfe = RFE(estimator=RandomForestClassifier(n_jobs=-1),n_features_to_select=5)
rfe.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1), n_features_to_select=5)

In [ ]:
rfe.ranking_

array([2, 1, 4, 1, 1, 1, 3, 1])

In [ ]:
rfe = RFE(estimator=RandomForestClassifier(n_jobs=-1),n_features_to_select=6)
rfe.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1), n_features_to_select=6)

In [ ]:
rfe.ranking_

array([1, 1, 3, 1, 1, 1, 2, 1])

In [ ]:
rfe = RFE(estimator=RandomForestClassifier(n_jobs=-1),n_features_to_select=7)
rfe.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1), n_features_to_select=7)

In [ ]:
rfe.ranking_

array([1, 1, 2, 1, 1, 1, 1, 1])

In [ ]:
rfe = RFE(estimator=RandomForestClassifier(n_jobs=-1),n_features_to_select=3)
rfe.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1), n_features_to_select=3)

In [ ]:
rfe.ranking_

array([4, 1, 6, 1, 1, 3, 5, 2])

In [ ]:
rfe = RFE(estimator=RandomForestClassifier(n_jobs=-1),n_features_to_select=2)
rfe.fit(X_train,y_train)

RFE(estimator=RandomForestClassifier(n_jobs=-1), n_features_to_select=2)

In [ ]:
rfe.ranking_

array([5, 1, 7, 2, 1, 4, 6, 3])

In [ ]:
df.drop('Outcome',inplace=True, axis=1)

In [ ]:
features = df.columns
features

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

#USING MODEL TO SELECT FEATURES-EMBEDDED METHODS

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.07)
lasso.fit(X_train, y_train)
y_pred1 = lasso.predict(X_test)
mean_squared_error = np.mean((y_pred1 - y_test)**2)
print("MSE on test set",mean_squared_error)
lasso_coeff = pd.DataFrame({"features":features,"coeff":lasso.coef_})
print(lasso_coeff.sort_values("coeff"))

MSE on test set 0.14255638268923365
                   features     coeff
2             BloodPressure  0.000000
6  DiabetesPedigreeFunction  0.000000
4                   Insulin  0.000691
7                       Age  0.001792
3             SkinThickness  0.004653
1                   Glucose  0.005289
5                       BMI  0.008040
0               Pregnancies  0.023627


#Ridge Method

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import Ridge
Ridge = Ridge(alpha=10)
Ridge.fit(X_train, y_train)
y_pred1 = Ridge.predict(X_test)
mean_squared_error = np.mean((y_pred1 - y_test)**2)
print("MSE on test set",mean_squared_error)
lasso_coeff = pd.DataFrame({"features":features,"coeff":Ridge.coef_})
print(lasso_coeff.sort_values("coeff"))

MSE on test set 0.1433752424615381
                   features     coeff
2             BloodPressure -0.000051
4                   Insulin  0.000641
7                       Age  0.001272
3             SkinThickness  0.004685
1                   Glucose  0.005190
5                       BMI  0.008754
0               Pregnancies  0.032726
6  DiabetesPedigreeFunction  0.094764


#Filter method

In [ ]:
from sklearn.feature_selection import SelectKBest #information gain
from sklearn.feature_selection import chi2

In [ ]:
##Apply SelectKBest Algorithm
ordered_rank_features = SelectKBest(score_func = chi2, k=4)
ordered_feature = ordered_rank_features.fit(X,Y)

In [ ]:
ordered_feature

SelectKBest(k=4, score_func=<function chi2 at 0x7fe336f7bdc0>)

In [ ]:
df_score = pd.DataFrame(ordered_feature.scores_, columns=['Score'])
df_columns = pd.DataFrame(df.columns)

In [ ]:
feature_rank = pd.concat([df_columns,df_score],axis=1)

In [ ]:
feature_rank

Features        Score
0               Pregnancies   134.739302
1                   Glucose  1439.168619
2             BloodPressure    47.267258
3             SkinThickness   181.546053
4                   Insulin  6107.908339
5                       BMI   111.489994
6  DiabetesPedigreeFunction     5.392682
7                       Age   181.303689

In [ ]:
feature_rank.columns = ['Features', 'Score']

In [ ]:
feature_rank

Features        Score
0               Pregnancies   134.739302
1                   Glucose  1439.168619
2             BloodPressure    47.267258
3             SkinThickness   181.546053
4                   Insulin  6107.908339
5                       BMI   111.489994
6  DiabetesPedigreeFunction     5.392682
7                       Age   181.303689

In [ ]:
feature_rank.nlargest(4,'Score')

Features        Score
4        Insulin  6107.908339
1        Glucose  1439.168619
3  SkinThickness   181.546053
7            Age   181.303689

In [ ]:
feature_rank.nlargest(5,'Score')

Features        Score
4        Insulin  6107.908339
1        Glucose  1439.168619
3  SkinThickness   181.546053
7            Age   181.303689
0    Pregnancies   134.739302

In [ ]:
feature_rank.nlargest(6,'Score')

Features        Score
4        Insulin  6107.908339
1        Glucose  1439.168619
3  SkinThickness   181.546053
7            Age   181.303689
0    Pregnancies   134.739302
5            BMI   111.489994

In [ ]:
feature_rank.nlargest(7,'Score')

Features        Score
4        Insulin  6107.908339
1        Glucose  1439.168619
3  SkinThickness   181.546053
7            Age   181.303689
0    Pregnancies   134.739302
5            BMI   111.489994
2  BloodPressure    47.267258

#Anova feature selection

In [ ]:
from sklearn.feature_selection import f_classif


In [ ]:
from sklearn.feature_selection import ReliefF

ImportError: ignored

In [ ]:
##Apply SelectKBest Algorithm
ordered_rank_features = SelectKBest(score_func = f_classif, k=8)
ordered_feature = ordered_rank_features.fit(X,Y)

In [ ]:
df_score = pd.DataFrame(ordered_feature.scores_, columns=['Score'])
df_columns = pd.DataFrame(df.columns)


In [ ]:
ordered_feature.scores_

array([ 71.01022216, 249.92394858,  24.04856687,  73.08996392,
       126.97145535,  84.7222798 ,  23.8713002 ,  46.14061124])

In [ ]:
feature_rank = pd.concat([df_columns,df_score],axis=1)

In [ ]:
feature_rank

0       Score
0               Pregnancies   71.010222
1                   Glucose  249.923949
2             BloodPressure   24.048567
3             SkinThickness   73.089964
4                   Insulin  126.971455
5                       BMI   84.722280
6  DiabetesPedigreeFunction   23.871300
7                       Age   46.140611

In [ ]:
feature_rank.nlargest(4,'Score')

0       Score
1        Glucose  249.923949
4        Insulin  126.971455
5            BMI   84.722280
3  SkinThickness   73.089964

In [ ]:
feature_rank.nlargest(5,'Score')

0       Score
1        Glucose  249.923949
4        Insulin  126.971455
5            BMI   84.722280
3  SkinThickness   73.089964
0    Pregnancies   71.010222

In [ ]:
feature_rank.nlargest(6,'Score')

0       Score
1        Glucose  249.923949
4        Insulin  126.971455
5            BMI   84.722280
3  SkinThickness   73.089964
0    Pregnancies   71.010222
7            Age   46.140611

In [ ]:
feature_rank.nlargest(7,'Score')

0       Score
1        Glucose  249.923949
4        Insulin  126.971455
5            BMI   84.722280
3  SkinThickness   73.089964
0    Pregnancies   71.010222
7            Age   46.140611
2  BloodPressure   24.048567

In [ ]:
from ReliefF import ReliefF
import numpy as np
from sklearn import datasets
import pandas as pd

#example of 2 class problem

fs = ReliefF(n_neighbors=3, n_features_to_keep=4)
X_train = fs.fit_transform(X, Y)
print(X_train)
print("--------------")
print("(No. of tuples, No. of Columns before ReliefF) : "+str(X.shape)+
      "\n(No. of tuples , No. of Columns after ReliefF) : "+str(X_train.shape))



[[102.5  29.    1.   66. ]
 [ 94.   23.    1.   66. ]
 [102.5  27.    5.   74. ]
 ...
 [169.5  32.    6.   92. ]
 [169.5  31.    9.   74. ]
 [169.5  32.    1.   60. ]]
--------------
(No. of tuples, No. of Columns before ReliefF) : (768, 8)
(No. of tuples , No. of Columns after ReliefF) : (768, 4)


In [ ]:
fs.top_features

array([4, 3, 0, 2, 7, 1, 5, 6])

In [ ]:
fs.tree

In [ ]:
##Apply SelectKBest Algorithm
ordered_rank_features1 = SelectKBest(score_func = ReliefF, k=8)
ordered_feature1 = ordered_rank_features1.fit(X,Y)


In [ ]:
ordered_feature1.fit_transform(X,Y)

TypeError: ignored

In [ ]:
ordered_feature1.scores_

array(<ReliefF.ReliefF.ReliefF object at 0x7fe336ef6b20>, dtype=object)

In [ ]:
!pip install ReliefF

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.1/48.1 kB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for ReliefF: filename=ReliefF-0.1.2-py3-none-any.whl size=6317 sha256=93dbca91990ff55e049f3c5332ec8bd6a3b16e4d4ca1e5a4f4ce4cb64af7461f
  Stored in directory: /root/.cache/pip/wheels/9a/70/5f/268f6b39a1e1d9f31d0f8af78cef10fdfa3fb27f9eeeaf70b4
Successfully built ReliefF


In [ ]:
r = ReliefF(n_neighbors=1,n_features_to_keep= 4)
X1 = r.fit_transform(X,Y)

In [ ]:
X1

array([[102.5,  29. ,   1. ,  66. ],
       [ 94. ,  23. ,   1. ,  66. ],
       [102.5,  27. ,   5. ,  74. ],
       ...,
       [169.5,  32. ,   6. ,  92. ],
       [169.5,  31. ,   9. ,  74. ],
       [169.5,  32. ,   1. ,  60. ]])

In [ ]:
r = ReliefF(n_neighbors=1,n_features_to_keep= 5)
X2 = r.fit_transform(X,Y)

In [ ]:
X2

array([[102.5,  29. ,   1. ,  66. ,  31. ],
       [ 94. ,  23. ,   1. ,  66. ,  21. ],
       [102.5,  27. ,   5. ,  74. ,  30. ],
       ...,
       [169.5,  32. ,   6. ,  92. ,  66. ],
       [169.5,  31. ,   9. ,  74. ,  43. ],
       [169.5,  32. ,   1. ,  60. ,  47. ]])

In [ ]:
r = ReliefF(n_neighbors=1,n_features_to_keep= 6)
X3 = r.fit_transform(X,Y)

In [ ]:
X3

array([[102.5,  29. ,   1. ,  66. ,  31. ,  85. ],
       [ 94. ,  23. ,   1. ,  66. ,  21. ,  89. ],
       [102.5,  27. ,   5. ,  74. ,  30. , 116. ],
       ...,
       [169.5,  32. ,   6. ,  92. ,  66. , 190. ],
       [169.5,  31. ,   9. ,  74. ,  43. , 170. ],
       [169.5,  32. ,   1. ,  60. ,  47. , 126. ]])

In [ ]:
r = ReliefF(n_neighbors=1,n_features_to_keep= 7)
X4 = r.fit_transform(X,Y)

In [ ]:
X4

array([[102.5,  29. ,   1. , ...,  31. ,  85. ,  26.6],
       [ 94. ,  23. ,   1. , ...,  21. ,  89. ,  28.1],
       [102.5,  27. ,   5. , ...,  30. , 116. ,  25.6],
       ...,
       [169.5,  32. ,   6. , ...,  66. , 190. ,  35.5],
       [169.5,  31. ,   9. , ...,  43. , 170. ,  44. ],
       [169.5,  32. ,   1. , ...,  47. , 126. ,  30.1]])

In [ ]:
X4[0]

array([102.5,  29. ,   1. ,  66. ,  31. ,  85. ,  26.6])

In [ ]:
from sklearn.feature_selection import mutual_info_classif
##Apply SelectKBest Algorithm
ordered_rank_features = SelectKBest(score_func = mutual_info_classif, k=8)
ordered_feature = ordered_rank_features.fit(X,Y)

In [ ]:
df_score = pd.DataFrame(ordered_feature.scores_, columns=['Score'])
df_columns = pd.DataFrame(df.columns)

In [ ]:
ordered_feature.scores_

array([0.06775485, 0.13661502, 0.04430014, 0.14689108, 0.3295931 ,
       0.07659914, 0.00895649, 0.06653208])

In [ ]:
feature_rank = pd.concat([df_columns,df_score],axis=1)

In [ ]:
feature_rank.nlargest(4,'Score')

0     Score
4        Insulin  0.329593
3  SkinThickness  0.146891
1        Glucose  0.136615
5            BMI  0.076599

In [ ]:
feature_rank.nlargest(5,'Score')

0     Score
4        Insulin  0.329593
3  SkinThickness  0.146891
1        Glucose  0.136615
5            BMI  0.076599
0    Pregnancies  0.067755

In [ ]:
feature_rank.nlargest(6,'Score')

0     Score
4        Insulin  0.329593
3  SkinThickness  0.146891
1        Glucose  0.136615
5            BMI  0.076599
0    Pregnancies  0.067755
7            Age  0.066532

In [ ]:
feature_rank.nlargest(7,'Score')

0     Score
4        Insulin  0.329593
3  SkinThickness  0.146891
1        Glucose  0.136615
5            BMI  0.076599
0    Pregnancies  0.067755
7            Age  0.066532
2  BloodPressure  0.044300

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import Lasso

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [ ]:
pipeline = Pipeline([
                     ('scaler',StandardScaler()),
                     ('model',Lasso())
])

In [ ]:
search = GridSearchCV(pipeline,
                      {'model__alpha':np.arange(0.1,10,0.1)},
                      cv = 5, scoring="neg_mean_squared_error",verbose=3
                      )

In [ ]:
search.fit(X_train,y_train)

Fitting 5 folds for each of 99 candidates, totalling 495 fits
[CV 1/5] END .................model__alpha=0.1;, score=-0.151 total time=   0.0s
[CV 2/5] END .................model__alpha=0.1;, score=-0.198 total time=   0.0s
[CV 3/5] END .................model__alpha=0.1;, score=-0.152 total time=   0.0s
[CV 4/5] END .................model__alpha=0.1;, score=-0.183 total time=   0.0s
[CV 5/5] END .................model__alpha=0.1;, score=-0.179 total time=   0.0s
[CV 1/5] END .................model__alpha=0.2;, score=-0.201 total time=   0.0s
[CV 2/5] END .................model__alpha=0.2;, score=-0.224 total time=   0.0s
[CV 3/5] END .................model__alpha=0.2;, score=-0.196 total time=   0.0s
[CV 4/5] END .................model__alpha=0.2;, score=-0.207 total time=   0.0s
[CV 5/5] END .................model__alpha=0.2;, score=-0.212 total time=   0.0s
[CV 1/5] END .model__alpha=0.30000000000000004;, score=-0.222 total time=   0.0s
[CV 2/5] END .model__alpha=0.30000000000000004;

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', Lasso())]),
             param_grid={'model__alpha': array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6,
       2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9,
       4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2,
       5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5,
       6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8,
       7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1,
       9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])},
             scoring='neg_mean_squared_error', verbose=3)

In [ ]:
coefficients = search.best_estimator_.named_steps['model'].coef_

In [ ]:
importance = np.abs(coefficients)

In [ ]:
importance

array([0.        , 0.14225134, 0.        , 0.        , 0.        ,
       0.02988647, 0.        , 0.        ])